name: Delop node Application
on:
    push:
        branches: ["master"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image
              run: docker build -t hieupc05/mui-shopdev --build-arg NODE_ENV=production --build-arg VITE_SERVER_PROD=${{secrets.VITE_SERVER_PROD}} --build-arg VITE_apiKey=${{secrets.VITE_apiKey}} --build-arg VITE_authDomain=${{secrets.VITE_authDomain}} --build-arg VITE_projectId=${{secrets.VITE_projectId}} --build-arg VITE_storageBucket=${{secrets.VITE_storageBucket}} --build-arg VITE_messagingSenderId=${{secrets.VITE_messagingSenderId}} --build-arg VITE_appId=${{secrets.VITE_appId}} --build-arg VITE_measurementId=${{secrets.VITE_measurementId}} .
            - name: Publish Image to docker hub
              run: docker push hieupc05/mui-shopdev:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull hieupc05/mui-shopdev:latest

            - name: Delete old container
              run: docker rm -f ui-shopdev || true

            - name: Run Shopdev Container
              run: docker run -d --name ui-shopdev -p 80:80 -p 443:443 -v $(pwd)/certbot/conf:/etc/letsencrypt -v $(pwd)/certbot/www:/var/www/certbot hieupc05/mui-shopdev:latest

            - name: Run Certbot Container
              run: docker run --name certbot -v $(pwd)/certbot/conf:/etc/letsencrypt -v $(pwd)/certbot/www:/var/www/certbot certbot/certbot certonly --webroot -w /var/www/certbot --force-renewal --email hoanghieuss3344@gmail.com -d shop.izsports.online --agree-tos
