name: Delop node Application 
on: 
    push: 
        branches: ["main"]
jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub 
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build Docker Image 
              run: docker build -t hieupc05/mui-shopdev --build-arg VITE_SERVER_PROD='${{secrets.VITE_SERVER_PROD}}' .
            - name: Publish Image to docker hub 
              run: docker push hieupc05/mui-shopdev:latest 

    deploy: 
        needs: build 
        runs-on: self-hosted
        steps: 
            - name: Pull image from docker hub 
              run: docker pull hieupc05/mui-shopdev:latest
            - name: Delete old container 
              run: docker rm -rf ui-shopdev || true
            - name: Run docker container 
              run: docker run -d -p 5173:80 --name ui-shopdev mui-shopdev 